version: "3"
services:
  db:
    image: mysql
    restart: always
    expose:
      - "3306"
    env_file:
      - ./env/db.env.example
    volumes:
      - /home/user/db/mysql/data:/var/lib/mysql
      - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro

  apiserver:
    image: apiserver
    restart: always
    depends_on:
      - db
    expose:
      - "8080"
    env_file:
      - ./env/apiserver.env.example

  next:
    image: next
    restart: always
    depends_on:
      - apiserver
    ports:
      - "3000:3000"
    env_file:
      - ./env/next.env.example
