version: "3"
services:
  db:
    image: mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - /home/user/db/mysql/data:/var/lib/mysql
      - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro

  apiserver:
    image: apiserver
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/apiserver
    ports:
      - "8080:8080"
