import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { Container, Button } from "@mui/material";
import { signIn, signOut, useSession } from "next-auth/client";
import IMenu from "../lib/model/IMenu";

const Home: NextPage<{ menu: IMenu[] }> = ({ menu }) => {
  const [session, loading] = useSession();

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {!session && (
          <>
            Not signed in <br />
            <Button variant="contained" onClick={() => signIn()}>
              Sign in
            </Button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user?.email} <br />
            <Button variant="outlined" color="error" onClick={() => signOut()}>
              Sign out
            </Button>
          </>
        )}
        {JSON.stringify(menu)}
      </Container>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("http://localhost:8080/menucategory");
  const data: IMenu[] = await res.json();

  return {
    props: {
      menu: data,
    },
  };
};

export default Home;
